// let nome = prompt("qual é o seu nome");

// let idade = prompt("quantos anos voçê tem?")

// alert (`Olá, ${nome}! voçê tem ${idade} anos!`)

// confirm()

// let repost = confirm("você tem certeza que deseja sair?")
// console.log(reposta)



// const nomeDoUsuário = prompt("qualé seu nome?");
// const profissaoDoUsuário = prompt("qual é a sua profissão");

// alert(`olá , ${nomeDoUsuário}! que interessante saber que você trabalha com ${profissaoDoUsuário}. `);



let idade = 20;
let possuiCarteira = true;

if (idade >= 18 && possuiCarteira) {
    console.log("Pode dirigir");
} else if (nota >= 60) {
    console.log("precisa tirar a carteira.");
} else {
    console.log("Menor de Idade.");
}